instituciones/developer_2.0/compartido/historial-acciones-guardar.php

Este es un cambio transitorio mientras se terminar de organizar la tarea de codificar las páginas de acuerdo al código nuevo que se colocó en la BD Admin.

Medida transitoria para que los usuarios puedan acceder a la plataforma

---

instituciones/developer_2.0/admisiones/bd-conexion.php
instituciones/developer_2.0/admisiones/formulario.php
instituciones/developer_2.0/admisiones/index.php
instituciones/developer_2.0/directivo/inscripciones-pasar-estudiante.php
instituciones/developer_2.0/directivo/inscripciones.php

Sincronizar grados.
Nuevo estado al pasar el estudiante.
Añadir BD de admisiones en conexion-datos (.gitignore)

Cambios para mejorar la inscripción

---

instituciones/developer_2.0/acudiente/guardar.php
instituciones/developer_2.0/controlador/autentico.php
instituciones/developer_2.0/directivo/solicitudes.php

Estos cambios involucran las siguientes tablas.
- usuarios_intentos_fallidos
- general_solicitudes

Mover las tablas generales a la bd general

---

config-general/config.php

Se incluye variable nueva. Puede que se use más adelante. Este cambio fue para probar que el cambio de nombre en el repositorio remoto no afectaba el repo local.

SN-00 - Cambio simple.

---

main-app/compartido/index-contenido.php

Los usuarios podrán ver cuales fueron las ultimas paginas donde estuvieron y volver a ingresar

ultimas 5 paginas visitadas por los usuarios

---

main-app/compartido/guardar.php
main-app/compartido/sintia-funciones.php

Enviar al usuario a la pagina que corresponde dependiendo del tipo de usuario

Redireccionar al usuario a la pagina correspondiente

---

main-app/admisiones/admin-formulario-actualizar.php
main-app/admisiones/index-guardar.php

Se configura host para envió de correos automáticos al momento de general una inscripción

---

config-general/mensajes-informativos.php
main-app/directivo/guardar.php
main-app/directivo/usuarios-editar.php
main-app/directivo/usuarios-update.php

Crear archivo independiente para la actualización de los usuarios.

Mejorar la actualización de los usuarios.

---

main-app/compartido/peso.php

En esta tarea se le asigna el peso en GB a cada institución de forma dinámica

 Carga dinamica de peso por GB instituciones

---

main-app/directivo/estudiantes-nivelaciones.php

Pes2023-9 Ampliar pantalla de nivelaciones en matriculas al 100%.

---

main-app/compartido/ajax-nivelaciones-registrar.php
main-app/directivo/estudiantes-nivelaciones-registrar.php
main-app/directivo/guardar.php

Me demore mas de lo establecido por que el proceso  de ingresar nota de nivelación no estaba funcionando como debía.

PES2023-10 - Se valida X de eliminar nivelación y se hace mejora para dejar funcional el procedimiento.

---

config-general/assets/css/theme/light/theme_style.css
config-general/mensajes-informativos.php
main-app/class/CargaAcademica.php
main-app/compartido/head.php
main-app/directivo/cargas-guardar.php
main-app/directivo/cargas.php
main-app/directivo/includes/barra-superior-matriculas.php

Se evita que esté repetido el mismo docente con el mismo curso, grupo y asigntura.

Pes2023-57 - Evitar duplicar cargas académicas

---

main-app/directivo/includes/barra-superior-movimientos-financieros.php
main-app/directivo/movimientos-agregar.php
main-app/directivo/movimientos-editar.php
main-app/directivo/movimientos.php

falta revisión del código comentado para cambios de la barra superior modificada.

Pes2023-49 Ampliar pantalla en movimientos financieros al 100%

---

config-general/ejecutar-acciones/sintia-consultas.php
sql/pes2023_138.sql

Se agrega columna nueva a la tabla academico_matriculas `mat_tipo_matricula`
Se agrega columna nueva a la tabla academico_grados `gra_tipo`

Pes2023 138 agregar columnas nuevas

---

.gitignore
main-app/directivo/estudiantes.php
main-app/index.php

se elimino class table-scrollable de la tabla de matriculas

Pes2023 72 ver todas opciones matricula

---

main-app/class/Boletin.php
main-app/class/Estudiantes.php
main-app/compartido/matricula-boletin-curso-12.php

PES2023-117 - Se crea boletín para institución el tagui

---

main-app/compartido/matricula-boletin-curso-12.php
main-app/docente/comportamiento.php

**\------------------------Así se ve espacio donde se imprime las observaciones.------------------------/**
**\------------------------Así se ve espacio para las firmas.------------------------/**
**\------------------------Así se ve botón que guarda las observaciones institucionales.------------------------/**

PES2023-183 - Mejoras en boletín y observaciones múltiples.

---

main-app/directivo/cursos.php

Pes2023 241 se crea columna ver tipo curso

---

main-app/class/Estudiantes.php
main-app/class/servicios/MediaTecnicaServicios.php
main-app/class/servicios/Servicios.php
main-app/directivo/estudiantes.php

PES2023-243 -listar estudiantes de matricula individual

---

main-app/class/Grados.php
main-app/directivo/cursos.php
main-app/directivo/includes/barra-superior-cursos.php

PES2023-242 crear filtro por curso

---

main-app/estudiante/filtro-cargas.php

PES2023-245 listar materias mt estudiantes

---

main-app/compartido/matricula-libro-curso.php

HF - Mejora en libro final para icolven(MAIN)

---

main-app/docente/ajax-calificaciones-registrar.php

PES2023-262 - Mejora al guardar notas masivas de MEDIA TECNICA

---

main-app/class/Estudiantes.php
main-app/compartido/informes-generales-sabanas.php

PES2023-261 - Listar estudiantes en sabana con definitivas por periodo

---

main-app/docente/aspectos.php
main-app/docente/comportamiento.php
main-app/docente/indicadores-recuperar.php

PES2023-259 - Se listan estudiantes al recuperar indicadores

---

main-app/docente/estudiantes.php

PES2023-254 - Listar mis estudiantes MT

---

main-app/compartido/planilla-docentes.php

PES2023-255 - Listar estudiantes MT en planilla docentes

---

main-app/docente/notas-indicador.php

PES2023-263 - Listar estudiantes MT en notas por indicador

---

main-app/docente/evaluaciones-resultados.php

PES2023-266 - Se listan estudiantes en resultado de evaluaciones

---

main-app/docente/calificaciones-todas-rapido.php

PES2023-252 - Se listan estudiantes MT en calificar mas rápido

---

main-app/docente/calificaciones-todas.php

PES2023-251 - Se listan estudiantes MT en resumen de notas

---

main-app/docente/periodos-resumen.php

PES2023-264 - Se listan estudiantes de MT en resumen por periodos

---

main-app/directivo/cursos-editar.php

PES2023-109 -  Escoger formato del boletín 

---

main-app/compartido/reporte-notas.php
main-app/directivo/ajax-traer-cargas.php
main-app/directivo/informes-todos.php
main-app/directivo/notas-registradas-informes-filtros.php

PES2023-40 -Reporte de notas registradas

---

main-app/class/UsuariosPadre.php
main-app/compartido/guardar.php

PES2023-112 Mantener temas de usuario en todos los años

---

main-app/compartido/noticias-contenido.php
main-app/pagos-online/index.php
main-app/pagos-online/respuesta.php

PES2023-111 - Se activa opción de renovación y pago mediante plataforma

---

config-general/idiomas.php
main-app/acudiente/aspectos.php
main-app/acudiente/estudiantes.php
main-app/acudiente/reportes-disciplinarios.php
main-app/compartido/aspectos-estudiantiles-contenido.php
main-app/compartido/calificaciones-estudiante-contenido.php
main-app/compartido/cargas-carpetas-agregar-contenido.php
main-app/compartido/cargas-carpetas-editar-contenido.php
main-app/compartido/encabezado.php
main-app/compartido/estado-de-cuenta-contenido.php
main-app/compartido/index-contenido.php
main-app/compartido/matricula-contenido.php
main-app/compartido/menu.php
main-app/compartido/notas-actuales-contenido.php
main-app/compartido/noticias-agregar-contenido.php
main-app/compartido/noticias-contenido.php
main-app/compartido/periodos-resumen-estudiante-contenido.php
main-app/estudiante/aspectos.php
main-app/estudiante/reportes-disciplinarios.php

PES2023-45 - Traducir textos en estudiantes y acudientes

---

main-app/class/UsuariosPadre.php
main-app/directivo/includes/barra-superior-usuarios-anios.php
main-app/directivo/includes/barra-superior-usuarios.php
main-app/directivo/usuarios-anios.php

`INSERT INTO odermangroup_sintia_admin_dev.paginas_publicidad(pagp_id, pagp_pagina, pagp_tipo_usuario, pagp_disponible, pagp_top, pagp_lateral, pagp_footer, pagp_popup, pagp_url_youtube, pagp_modulo, pagp_ruta, pagp_palabras_claves, pagp_descripcion, pagp_parametro, pagp_navegable, pagp_crud) VALUES ('DT0201', 'Usuarios años', 5, 1, 1, 0, 1, 1, '', 7, 'usuario-anios.php', 'usuarios,años', NULL, 1, 1, NULL);`

PES2023-91 ver usuarios cada año

---

main-app/admisiones/formulario-guardar.php
main-app/admisiones/index-guardar.php
main-app/directivo/inscripciones.php

PES2023-286 - Mejoras para el módulo de inscripciones

---

config-general/config-admisiones.php
config-general/template-email-index-inscripcion.php
main-app/admisiones/admin-adjuntos-eliminar.php
main-app/admisiones/admin-formulario-actualizar.php
main-app/admisiones/admin-formulario-editar.php
main-app/admisiones/admision.php
main-app/admisiones/bd-conexion.php
main-app/admisiones/consultar-estado.php
main-app/admisiones/enviar-comprobante.php
main-app/admisiones/formulario-guardar.php
main-app/admisiones/index-guardar.php
main-app/admisiones/index.php
main-app/admisiones/menu.php
main-app/directivo/inscripciones.php

PES2023-287 - Se crea interfaz de inicio para admisiones y correcciones necesarias

---

main-app/class/Estudiantes.php
main-app/class/servicios/MediaTecnicaServicios.php
main-app/compartido/reportes-sabanas.php

PES2023-282 - Listar estudiantes MT en sabanas de informes

---

main-app/compartido/guardar.php

PES2023-213 Validar que campo compartidos cuando este vacio

---

main-app/compartido/informe-nivelaciones.php
main-app/directivo/estudiantes-nivelaciones-registrar.php

PES2023-284 -  Se listan estudiantes de MT en nivelaciones

---

main-app/compartido/informe-consolidad-final.php
main-app/directivo/estudiantes-consolidado-final-detalles.php

PES2023-283 - Se listan estudiantes de MT en consolidado final

---

main-app/compartido/ajax-mensajes.php
main-app/compartido/encabezado.php
main-app/compartido/sintia-funciones-js.php

Pes2023-44 No se ve opción enviar mensajes

---

main-app/docente/ajax-calificaciones-registrar.php
main-app/docente/aspectos.php

PES2023-297 - Guardar información de los aspectos académicos de docentes directores grupos

---

main-app/acudiente/estudiantes.php
main-app/compartido/notas-actuales-contenido.php
main-app/compartido/periodos-resumen-estudiante-contenido.php

PES2023-300 - Se listan materias de MT para los acudientes en resumen por periodos y definitivas actuales

---

main-app/compartido/informe-parcial-grupo-detalle.php

PES2023-303 - Se listan estudiantes en cursos de MT

---

config-general/constantes.php
config-general/mensajes-informativos.php
main-app/admisiones/admin-formulario-actualizar.php
main-app/admisiones/admin-formulario-editar.php
main-app/admisiones/index-guardar.php
main-app/class/EnviarEmail.php
main-app/compartido/guardar.php
main-app/recuperar-clave-guardar.php
tareas-auto.php

PES2023-294 Validar correos antes de enviar y agregar campos en tabla

---

main-app/compartido/ajax-comentarios-preguntas.php
main-app/compartido/clases-ver-contenido.php

PES2023-298 Guardar comentarios de clases

---

main-app/class/servicios/MediaTecnicaServicios.php
main-app/directivo/ajax-listar-estudiantes.php
main-app/directivo/cursos-actualizar.php
main-app/directivo/cursos-editar.php
main-app/directivo/cursos.php

PES2023-301 - Asignar masivamente estudiantes en curso mt

---

main-app/class/UsuariosPadre.php
main-app/compartido/ajax-listar-usuarios.php
main-app/compartido/cargas-carpetas-agregar-contenido.php
main-app/compartido/cargas-carpetas-editar-contenido.php

PES2023-320 - Al editar carpetas cargar usuarios de compartir a medida que se va escribiendo

---

main-app/directivo/informes-boletines.php

PES2023-309 - Se listan solo cursos grupales al imprimir el boletín

---

main-app/compartido/indicadores-perdidos-curso.php

PES2023-310 - Se listan estudiantes de MT en Indicadores perdidos

---

main-app/class/servicios/MediaTecnicaServicios.php
main-app/compartido/informe-parcial.php
main-app/estudiante/cargas.php

PES2023-308 -  Se listan materias de MT en informe parcial

---

main-app/compartido/matricula-certificado-areas-2.php
main-app/compartido/matricula-certificado-areas.php
main-app/compartido/matricula-certificado.php

Antes de aprobar este PR debe ser aprobado el PR #536

PES2023-311 - Se listan materias de MT en estudiantes de MT

---

main-app/directivo/periodos-resumen.php

PES2023-313 - Se listan estudiantes al consultar resumen por periodos en cursos MT

---

main-app/compartido/listado-estudiante.php

PES2023-316 - Se listan estudiantes para cursos de MT en informe #5

---

main-app/directivo/periodos-resumen.php
main-app/docente/aspectos.php
main-app/docente/calificaciones-registrar.php
main-app/docente/calificaciones-todas-rapido.php
main-app/docente/calificaciones-todas.php
main-app/docente/clases-registrar.php
main-app/docente/indicadores-recuperar.php
main-app/docente/periodos-resumen.php

Esta mejora la realiza por que nos dimos cuenta que al agregar unos estudiantes nuevos a un curso de MT, por alguna razón se rompía la consulta, al añadirle esas comillas simple consultaba normal

HF-MT - Mejora al consultar con ID del estudiante

---

config-general/config.php
main-app/compartido/excel-estudiantes.php
main-app/directivo/includes/barra-superior-matriculas.php
main-app/directivo/reportes-academicos-consultas.php

Esta mejora se hace porque al momento de exportar los estudiantes, toma los que están en estado 5(Inscripción) como matriculados o no matriculado y en la parte donde se listan los estudiantes sucede lo mismo

HF - Mejora para tener en cuenta los estudiantes en proceso de inscripción(DEVELOPER)

---

config-general/constantes.php
main-app/class/Sysjobs.php
main-app/compartido/generar-informe-jobs.php
main-app/compartido/job-generar-informe.php
main-app/docente/cargas.php

PES2023 332 Corrección informes generados

---

main-app/acudiente/aspectos.php
main-app/acudiente/estudiantes.php
main-app/acudiente/marketplace.php

PES2023-323 - Se validan warning faltantes para los acudientes

---

main-app/compartido/menu.php
main-app/docente/cargas.php

PES2023-321 - Se validan warning faltantes para los docentes

---

main-app/estudiante/cargas.php

PES2023-322 - Se validan warning faltantes para estudiantes

---

main-app/class/Sysjobs.php
main-app/compartido/excel-importar-estudiantes-job.php
main-app/compartido/generar-informe-jobs.php
main-app/directivo/job-excel-importar-estudiantes.php

link de acceso al ejecutor:  /app-sintia/main-app/compartido/excel-importar-estudiantes-job.php

PES2023 290 Job importar estudiantes

---

main-app/acudiente/aspectos.php
main-app/acudiente/estudiantes.php
main-app/acudiente/guardar.php
main-app/acudiente/reportes-disciplinarios.php
main-app/compartido/aspectos-estudiantiles-contenido.php
main-app/compartido/calificaciones-estudiante-contenido.php
main-app/compartido/informe-parcial.php
main-app/compartido/notas-actuales-contenido.php
main-app/compartido/periodos-resumen-estudiante-contenido.php
main-app/directivo/estudiantes.php
main-app/estudiante/verificar-carga.php
main-app/estudiante/verificar-usuario.php

PES2023-337 - Se encriptan parametros get para acudientes

---

config-general/idiomas.php
main-app/class/SubRoles.php
main-app/compartido/guardar-historial-acciones.php
main-app/compartido/menu.php
main-app/directivo/sub-roles-actualizar.php
main-app/directivo/sub-roles-agregar.php
main-app/directivo/sub-roles-editar.php
main-app/directivo/sub-roles-guardar.php
main-app/directivo/sub-roles.php
main-app/directivo/usuarios-editar.php
main-app/directivo/usuarios-update.php

PES2023 344,345,347 paginas gestión de sub Roles

---

main-app/class/SubRoles.php
main-app/directivo/sub-roles.php
main-app/directivo/usuarios-editar.php
main-app/directivo/usuarios-update.php

PES2023 356,385 No deja quitar roles y filtro por institución

---

main-app/compartido/reporte-disciplina-sacar.php

PES2023-362 Se corrigió warning y repetición de la letra s en el reporte

---

main-app/docente/guardar.php

PES2023-336 - Se quita consulta que carga variable sesión para cargas al configurar una carga

---

config-general/constantes.php
main-app/class/Sysjobs.php
main-app/compartido/generar-informe-jobs.php
main-app/docente/cargas.php

PES2023-392 Mejoras jobs

---

main-app/compartido/guardar.php
main-app/compartido/noticias-editar-contenido.php

pes2023-354 se envía el valor vacío de la imagen por defecto,

---

main-app/directivo/estudiantes-consolidado-final-detalles2.php
main-app/directivo/estudiantes-consolidado-final.php
main-app/directivo/estudiantes-nivelaciones-registrar2.php
main-app/directivo/estudiantes-nivelaciones.php

PES2023 339 Mejora consolidado final y Nivelacion

---

main-app/compartido/menu.php
main-app/controlador/salir.php

PES2023-355 - Se oculta en el menú la opción de G. Académica si no tiene una carga seleccionada

---

main-app/acudiente/marketplace.php
main-app/compartido/barra-superior-marketplace.php
main-app/compartido/cumplimentados.php
main-app/compartido/empresas-agregar-contenido.php
main-app/compartido/guardar.php
main-app/compartido/marketplace-contenido.php
main-app/compartido/mensajes-redactar-contenido.php
main-app/compartido/mensajes-ver-contenido.php
main-app/compartido/modal-acciones.php
main-app/compartido/modal-marketplace-detalles.php
main-app/compartido/noticias-agregar-contenido.php
main-app/compartido/noticias-editar-contenido.php
main-app/compartido/productos-agregar-contenido.php
main-app/compartido/productos-comprar-contenido.php
main-app/directivo/estudiantes.php
main-app/directivo/marketplace.php
main-app/docente/empresas-agregar.php
main-app/docente/marketplace.php
main-app/docente/productos-agregar.php
main-app/estudiante/marketplace.php

PES2023-367 - Se cambia barra lateral por barra superior y se le da el 100% a los productos
PES2023-370 - Se le da el mismo tamaño a los productos sin importar imagen o título
PES2023-371 - Se muestran detalles de los productos en ventana modal
PES2023-372 - Se añade plugin de editor para las descripciones del producto
PES2023-372 - Se añade plugin de editor al crear o editar una noticia
PES2023-368 - Se implementa servicio Epayco para pagos por marketplace
PES2023-378 - Se encriptan paramaetros URL de marketplace

PES2023 - Avance en historias de marketplace

---

main-app/directivo/includes/barra-superior-mps-categorias-productos.php
main-app/directivo/includes/consulta-paginacion-mps-categorias-productos.php
main-app/directivo/mps-categorias-productos-actualizar.php
main-app/directivo/mps-categorias-productos-aditar.php
main-app/directivo/mps-categorias-productos-agregar.php
main-app/directivo/mps-categorias-productos-eliminar.php
main-app/directivo/mps-categorias-productos-guardar.php
main-app/directivo/mps-categorias-productos.php

PES2023-377 - Se crea CRUD para las categorías de productos

---

main-app/compartido/menu.php

PES2023-374 - Se añaden items para administrar marketplaces

---

main-app/class/Estudiantes.php
main-app/class/Sysjobs.php
main-app/compartido/generar-informe-jobs.php
main-app/docente/cargas.php

PES2023 411 mejoras en el job

---

main-app/class/SubRoles.php
main-app/directivo/sub-roles-actualizar.php
main-app/directivo/sub-roles-editar.php
main-app/directivo/sub-roles.php

Pes2023 380 Orden de paginas activas y filtrado

---

main-app/docente/calificaciones-todas.php
main-app/docente/includes/barra-superior-informacion-actual.php

PES2023 350 Filtro panel información actual

---

main-app/compartido/clases-ver-contenido.php
main-app/directivo/dev-ejecutar-scripts-guardar.php
main-app/docente/clases-agregar.php
main-app/docente/clases-editar.php
main-app/docente/guardar.php

Pes2023 351 incluir campo hipervinculo en clases

---

config-general/idiomas.php
main-app/compartido/menu.php
main-app/docente/unidades-actualizar.php
main-app/docente/unidades-agregar.php
main-app/docente/unidades-editar.php
main-app/docente/unidades-eliminar.php
main-app/docente/unidades-guardar.php
main-app/docente/unidades.php

Pes2023 352 crud unidades tematicas docentes

---

main-app/directivo/includes/barra-superior-mps-categorias-servicios.php
main-app/directivo/includes/consulta-paginacion-mps-categorias-servicios.php
main-app/directivo/mps-categorias-servicios-actualizar.php
main-app/directivo/mps-categorias-servicios-aditar.php
main-app/directivo/mps-categorias-servicios-agregar.php
main-app/directivo/mps-categorias-servicios-eliminar.php
main-app/directivo/mps-categorias-servicios-guardar.php
main-app/directivo/mps-categorias-servicios.php

PES2023-373 - Se crea CRUD para las categorías de los servicios

---

main-app/compartido/marketplace-contenido.php
main-app/directivo/includes/barra-superior-mps-productos.php
main-app/directivo/includes/consulta-paginacion-mps-productos.php
main-app/directivo/mps-productos-actualizar.php
main-app/directivo/mps-productos-aditar.php
main-app/directivo/mps-productos-agregar.php
main-app/directivo/mps-productos-eliminar.php
main-app/directivo/mps-productos-guardar.php
main-app/directivo/mps-productos.php

PES2023-376 - Se crea CRUD para productos de marketplace

---

main-app/class/Modulos.php
main-app/class/SubRoles.php
main-app/directivo/ajax-dev-paginas-editar.php
main-app/directivo/ajax-guardar.php
main-app/directivo/dev-paginas-actualizar.php
main-app/directivo/dev-paginas-agregar.php
main-app/directivo/dev-paginas-editar.php
main-app/directivo/dev-paginas-guardar.php
main-app/directivo/dev-paginas.php
main-app/directivo/includes/barra-superior-dev-paginas.php
main-app/directivo/sub-roles.php
main-app/directivo/usuarios-editar.php
main-app/directivo/usuarios-update.php

Para esta historia traje commits necesarios de la historia PES2023-356 que trabajo Luiggi

PES2023-348 - Agrupar páginas equivalentes al asignar o editar roles

---

main-app/compartido/clases-ver-contenido.php
main-app/compartido/guardar.php
main-app/compartido/marketplace-contenido.php
main-app/compartido/modal-marketplace-detalles.php
main-app/directivo/auto-login.php
main-app/directivo/cargas.php
main-app/directivo/mps-categorias-productos-aditar.php
main-app/directivo/mps-categorias-productos-agregar.php
main-app/directivo/mps-categorias-productos.php
main-app/directivo/mps-categorias-servicios-aditar.php
main-app/directivo/mps-categorias-servicios-agregar.php
main-app/directivo/mps-categorias-servicios.php
main-app/directivo/mps-productos-actualizar.php
main-app/directivo/mps-productos-guardar.php
main-app/docente/clases-agregar.php
main-app/docente/clases-editar.php
main-app/docente/clases.php
main-app/docente/guardar.php
main-app/docente/unidades-agregar.php
main-app/docente/unidades-editar.php
main-app/docente/unidades.php
main-app/estudiante/evaluaciones-clave.php

PES2023-353 - Vincular clases a unidades

---

main-app/compartido/marketplace-contenido.php

Con este PR se soluciona el estiramiento de imágenes cuando alguna imagen es muy larga

PES2023-MPS - Mejora en tamaño de fotos del productos

---

main-app/directivo/excel-importar-movimientos.php
main-app/directivo/includes/info-academica.php
main-app/directivo/movimientos-importar.php
main-app/directivo/movimientos.php

PES2023-422 - Actualizar libreria excel al importar movimientos financieros(MAIN)

---

main-app/docente/calificaciones-todas.php

Pes2023 412 alinear cabecera con registros

---

main-app/directivo/excel-importar-movimientos.php
main-app/directivo/includes/info-academica.php
main-app/directivo/movimientos-importar.php
main-app/directivo/movimientos.php

PES2023-422 - Actualizar libreria excel al importar movimientos financieros(SPRINT-13)

---

main-app/compartido/do-crop.php
main-app/compartido/guardar.php
main-app/compartido/perfil-recortar-foto-contenido.php
main-app/compartido/sintia-funciones.php

Se identifico que el error solo estaba ocurriendo con los usuarios tipo DEV y se le dio solución

PES2023-420 - Se cierra la sesión al subir una foto de perfil

---

main-app/directivo/configuracion-sistema-guardar.php
main-app/directivo/configuracion-sistema.php
main-app/directivo/dev-instituciones-configuracion-actualizar.php
main-app/directivo/dev-instituciones-configuracion.php

PES2023-410 - Mejoras al generar informes docentes

---

main-app/compartido/funciones.js
main-app/docente/calificaciones-todas-rapido.php
main-app/docente/calificaciones-todas.php

PES2023-402 - Notificar cuando elimina nota (DEV)

---

main-app/compartido/funciones.js
main-app/compartido/guardar.php
main-app/compartido/productos-agregar-contenido.php
main-app/compartido/productos-comprar-contenido.php
main-app/pagos-online/index.php

Se implementaron mejoras adicionales:
- Agregar stock al agregar producto.
- Campo de total al comprar.
- Recalcular el valor a pagar en linea.

PES2023 - 442 - Cantidad al comprar un producto

---

config-general/assets/css/chat.css
main-app/directivo/ajax-buscador.php
main-app/directivo/ajax-chat.php
main-app/directivo/chat.php

PES2023-388 - Se crea interfaz gráfica para chat

---

config-general/assets/plugins/select2/js/select2.js
main-app/compartido/mensajes-redactar-contenido.php
main-app/directivo/movimientos-agregar.php
main-app/directivo/movimientos-editar.php

PES2023-391 - Cargar dinámicamente los usuarios en los select (DEV)

---

main-app/directivo/excel-importar-usuarios.php
main-app/directivo/usuarios-importar-excel.php

PES2023-395 - Se actualiza librería al exportar usuarios (DEV)

---

main-app/directivo/sub-roles-agregar.php
main-app/directivo/sub-roles-editar.php

PES2023-426 - Poder asignar todas las páginas a un rol (DEV)

---

main-app/directivo/chat.php

PES2023-389 funcionalidad basica del chat

---

main-app/class/SubRoles.php
main-app/directivo/sub-roles-actualizar.php
main-app/directivo/sub-roles-agregar.php
main-app/directivo/sub-roles-editar.php
main-app/directivo/sub-roles-guardar.php

PES2023-427 - Agregar usuarios al crear o editar los subroles

---

main-app/directivo/dev-ejecutar-scripts-guardar.php

PES2023-454 - Se guarda registro al ejecutar un script

---

main-app/class/Paginas.php
main-app/directivo/dev-paginas-actualizar.php
main-app/directivo/dev-paginas-agregar.php
main-app/directivo/dev-paginas-editar.php
main-app/directivo/dev-paginas-guardar.php
main-app/directivo/dev-paginas.php

PES2023-430 - Se agrega campo para gestionar páginas de dependencias al agregar y editar páginas (DEV)

---

config-general/assets/css/chat.css
config-general/assets/css/chat2.css
config-general/assets/js/chat.js
config-general/constantes.php
main-app/compartido/body.php
main-app/compartido/chat-guardar-imagen-ajax.php
main-app/compartido/footer.php
main-app/compartido/funciones.js
main-app/compartido/head.php
main-app/directivo/ajax-buscador.php
main-app/directivo/ajax-chat-usuarios.php
main-app/directivo/chat.php
main-app/directivo/chat2.php

Hasta el momento tenemos la versión estable del chat.
Está funcionando en chat2.php
Queda pendiente lo siguiente:
1. El visto
2. El scroll que no se baje cuando me escribe el mismo usuario en el cual estoy viendo.
3. El enter para enviar mensajes.
4. Icono flotante que me lleve al chat (Que muestre el número de los mensajes)
5. Ajustar la foto del usuario loguedo en la pantalla del chat para que no se desborde.
6. Definir las constantes para la URL, el puerto y demás.

Pes2023 390 chat avanzado

---

main-app/compartido/noticias-contenido.php
main-app/controlador/autentico.php

**HF - Modificar lógica de noticias para permitir noticias globales a todas las instituciones.**
Esto es necesario para publicar una noticia global avisando sobre los cambios que se vienen.

HF - Modificar lógica de noticias para permitir noticias globales.

---

main-app/compartido/informe-parcial.php
main-app/compartido/notas-actuales-contenido.php

PES2023-524 - Implementar en acudientes opción de ver notas cualitativa, según la configuración de la institución

---

main-app/directivo/includes/barra-superior-usuarios.php
main-app/directivo/includes/usuarios-editar-info-basica.php
main-app/directivo/sub-roles.php
main-app/directivo/usuarios.php

Algunas paginas deberían ser asignables aunque no sean navegables para poder validar permisos ahí.
**Ejemplo:** autologin, eliminar, cambiar estados de solicitudes, etc.

PES-436 - Validar roles a nivel de acciones en G. Administrativa

---

config-general/idiomas.php
main-app/class/Movimientos.php
main-app/compartido/funciones.js
main-app/compartido/menu.php
main-app/directivo/includes/barra-superior-movimientos-financieros-editar.php
main-app/directivo/items-actualizar.php
main-app/directivo/items-agregar.php
main-app/directivo/items-editar.php
main-app/directivo/items-eliminar.php
main-app/directivo/items-guardar.php
main-app/directivo/items.php
main-app/directivo/movimientos-actualizar.php
main-app/directivo/movimientos-agregar.php
main-app/directivo/movimientos-editar.php
main-app/directivo/movimientos-factura-venta.php
main-app/directivo/movimientos-guardar.php
main-app/directivo/movimientos.php

PES-600 - CRUD a items

---

config-general/constantes.php
main-app/compartido/informe-parcial.php
main-app/compartido/matricula-boletin-curso-8.php
main-app/compartido/matricula-contenido.php
main-app/compartido/matricula-libro-curso.php
main-app/compartido/reportes-sabanas.php
main-app/directivo/cargas.php
main-app/directivo/estudiantes-actualizar.php
main-app/directivo/estudiantes.php
main-app/directivo/includes/formulario-configuracion-contenido.php
main-app/directivo/includes/pasos-matricula.php

En los siguientes archivos quedaron validaciones por institución
estado-de-cuenta.php
informe-parcial.php
matricula-boletin-curso-8.php
estudiantes-actualizar.php
estudiantes-editar.php
estudiantes-guardar.php
estudiantes.php

PES-540 - Configurar que el paso a paso matrículas no valide por institución

---

config-general/idiomas.php
main-app/class/Scripts.php
main-app/compartido/menu.php
main-app/directivo/dev-ejecutar-scripts.php
main-app/directivo/dev-scripts-detalles.php
main-app/directivo/dev-scripts.php

PES-455 - Opción de listar y ver detalles del historial de scripts

---

main-app/class/Movimientos.php
main-app/directivo/abonos-recibo-caja.php
main-app/directivo/abonos.php

PES-604 - Se crea comprobante de pago a abonos

---

config-general/constantes.php
main-app/class/Movimientos.php
main-app/directivo/cotizacion-imprimir.php

Para probar entrar al siguiente enlace
http://localhost/app-sintia/main-app/directivo/cotizacion-imprimir.php?id=Q09UMDAwMQ==![image]
(https://github.com/oderman-group/app-sintia/assets/29340783/2348de16-a1e5-4606-9d89-5fc8c738cb34)

PES-606 - Se crea diseño de impresión para cotizaciones

---

config-general/constantes.php
config-general/idiomas.php
main-app/class/Movimientos.php
main-app/compartido/menu.php
main-app/directivo/ajax-guardar-items.php
main-app/directivo/ajax-traer-items.php
main-app/directivo/factura-recurrente-actualizar.php
main-app/directivo/factura-recurrente-agregar.php
main-app/directivo/factura-recurrente-editar.php
main-app/directivo/factura-recurrente-eliminar.php
main-app/directivo/factura-recurrente-guardar.php
main-app/directivo/factura-recurrente.php
main-app/directivo/movimientos-agregar.php
main-app/directivo/movimientos-editar.php
main-app/js/Movimientos.js

PES-605 Adelanto de factura recurrente cronjob

---

main-app/admisiones/formulario-guardar.php
main-app/class/Inscripciones.php
main-app/directivo/inscripciones-formulario-guardar.php

Correción que hacía falta para guardar formularios

HTF - Corrección al guardar los datos del formulario

---

config-general/constantes.php
config-general/idiomas.php
main-app/class/Movimientos.php
main-app/compartido/generar-facturas-jobs.php
main-app/compartido/menu.php
main-app/directivo/ajax-guardar-items.php
main-app/directivo/ajax-traer-items.php
main-app/directivo/factura-recurrente-actualizar.php
main-app/directivo/factura-recurrente-agregar.php
main-app/directivo/factura-recurrente-editar.php
main-app/directivo/factura-recurrente-eliminar.php
main-app/directivo/factura-recurrente-guardar.php
main-app/directivo/factura-recurrente.php
main-app/directivo/movimientos-agregar.php
main-app/directivo/movimientos-editar.php
main-app/js/Movimientos.js

PES-605 - Opción de factura recurrente cronjob

---

main-app/class/Movimientos.php
main-app/directivo/abonos-actualizar.php
main-app/directivo/abonos-agregar.php
main-app/directivo/abonos-editar.php
main-app/directivo/abonos-guardar.php
main-app/directivo/abonos.php
main-app/directivo/movimientos-actualizar.php
main-app/directivo/movimientos-editar.php
main-app/directivo/movimientos.php

Pes 677 feedback para el modulo financieros

---

main-app/admisiones/formulario-guardar.php
main-app/class/servicios/MediaTecnicaServicios.php
main-app/directivo/estudiantes-actualizar.php

Se quita código por el que salia error al guardar la información

HTF- Se quita codigo innecesario que perjudicaba el codigo

---

main-app/compartido/matricula-boletin-curso-2.php
main-app/directivo/cursos-actualizar-cargas.php
main-app/directivo/ingresar-datos-bd.php

Se corrige soporte solicitado por profe Marlene de G. Innovadores
Se corrige error reportado por Jess al utilizar botón "actualizar con las cargas" en intensidad por cursos
Se corrige error de información incompleta en cursos al crear nuevo año para una institución

HTF - Mejora para materias perdidas en boletín de G. innovadores

---

main-app/class/EvaluacionGeneral.php
main-app/compartido/menu.php
main-app/directivo/evaluacion-actualizar.php
main-app/directivo/evaluacion-agregar.php
main-app/directivo/evaluacion-editar.php
main-app/directivo/evaluacion-eliminar.php
main-app/directivo/evaluacion-guardar.php
main-app/directivo/evaluaciones.php

PES-530 - creación CRUD  para evaluaciones

---

config-general/constantes.php
main-app/class/PreguntaGeneral.php
main-app/compartido/menu.php
main-app/directivo/pregunta-actualizar.php
main-app/directivo/pregunta-agregar.php
main-app/directivo/pregunta-editar.php
main-app/directivo/pregunta-eliminar.php
main-app/directivo/pregunta-guardar.php
main-app/directivo/preguntas.php

PES-531 Crud tabla preguntas

---

main-app/directivo/includes/barra-superior-reservar-cupo.php
main-app/directivo/reservar-cupo.php

PES-665 - Permitir filtro por respuestas en reserva de cupos

---

main-app/compartido/reporte-movimientos.php

PES-590 - Se actualiza apariencia de informe de movimientos financieros

---

config-general/constantes.php
main-app/class/SubRoles.php
main-app/directivo/dev-paginas-actualizar.php
main-app/directivo/dev-paginas-agregar.php
main-app/directivo/dev-paginas-editar.php
main-app/directivo/dev-paginas-guardar.php

PES-666 - Se implementa columna para preguntar si una página es asignable a los roles, diferente de navegable

---

main-app/compartido/cambiar-clave-contenido.php
main-app/js/CambiarClave.js

PES-577 - Al cambiar la clave me diga si es correcta y si la nueva clave coinciden y es válida

---

main-app/class/CargaAcademica.php
main-app/directivo/cargas-transferir-actualizar.php
main-app/directivo/cargas-transferir-modal.php
main-app/directivo/cargas-transferir.php
main-app/js/Cargas.js

PES-656 - Poder transferir carga de forma parcial

---

main-app/directivo/dev-crear-bd-informacion.php
main-app/directivo/dev-crear-nueva-bd.php
main-app/directivo/ingresar-datos-bd.php

En esta historia aparecen los commit de la historia 578 pero esos ya están en TEST, los archivos si aparecen netamente los 3 que trabaje en esta historia y la release que está desactualizada en TEST
También se añadió la relación entre usuario y acudiente al crear una nueva institución

PES-667 - Al crear una nueva institución, designar un directivo primario

---

main-app/class/CargaAcademica.php
main-app/directivo/ajax-validar-cargas.php
main-app/directivo/cursos-promocionar-estudiantes-detalles.php
main-app/directivo/cursos-promocionar-estudiantes.php
main-app/directivo/cursos.php
main-app/directivo/includes/barra-superior-cursos.php
main-app/js/Cursos.js

PES-655 - Paso intermedio al promover estudiantes

---

main-app/directivo/includes/usuarios-editar-info-basica.php
main-app/js/Utilidades.js

Pes 686 d opcion de subroles en editar usuarios sin modulo

---

main-app/compartido/matricula-libro-curso-1.php
main-app/compartido/matricula-libro-curso-2.php
main-app/directivo/configuracion-sistema-guardar.php
main-app/directivo/cursos.php
main-app/directivo/estudiantes.php
main-app/directivo/includes/formulario-configuracion-contenido.php
main-app/directivo/informe-libro-cursos-modal.php

PES-712 - Se crea libro definitivo formato 2

---

config-general/constantes.php
config-general/idiomas.php
main-app/class/Movimientos.php
main-app/compartido/menu.php
main-app/directivo/impuestos-actualizar.php
main-app/directivo/impuestos-agregar.php
main-app/directivo/impuestos-editar.php
main-app/directivo/impuestos-eliminar.php
main-app/directivo/impuestos-guardar.php
main-app/directivo/impuestos.php
main-app/js/Movimientos.js

PES-710 - Dscuentos e Impuestos (AVANCES)

---

main-app/compartido/matricula-certificado-areas-2.php
main-app/directivo/disciplina-faltas.php
main-app/directivo/reportes-sacar-filtro-modal.php

Tambien se añade commit con solicitud de soporte solicitada por G. Innovadores

HTF - Se agrega nuevas funciones sugeridas por icolven

---

config-general/constantes.php
config-general/idiomas.php
main-app/class/Movimientos.php
main-app/compartido/menu.php
main-app/directivo/abonos-agregar.php
main-app/directivo/abonos-concepto-eliminar.php
main-app/directivo/abonos-editar.php
main-app/directivo/abonos.php
main-app/directivo/ajax-cambiar-estado-factura.php
main-app/directivo/ajax-cambiar-subtotal-concepto.php
main-app/directivo/ajax-guardar-abono.php
main-app/directivo/ajax-guardar-descripcion-concepto.php
main-app/directivo/ajax-traer-facturas.php
main-app/directivo/factura-recurrente-agregar.php
main-app/directivo/factura-recurrente-editar.php
main-app/directivo/movimientos-agregar.php
main-app/directivo/movimientos-editar.php
main-app/js/Movimientos.js

PES-711 - Feedback sprint demo 21

---

main-app/compartido/menu.php
main-app/directivo/includes/barra-superior-movimientos-financieros.php
main-app/directivo/movimientos.php
main-app/js/Movimientos.js

PES-685 - Filtros por fecha y resumen de valores facturados

---

main-app/class/Movimientos.php
main-app/directivo/ajax-cambiar-subtotal.php
main-app/directivo/ajax-guardar-items.php
main-app/directivo/ajax-traer-items.php
main-app/directivo/factura-recurrente-agregar.php
main-app/directivo/factura-recurrente-editar.php
main-app/directivo/movimientos-agregar.php
main-app/directivo/movimientos-editar.php
main-app/directivo/movimientos-factura-venta.php
main-app/js/Movimientos.js

PES-710 -  Descuentos e impuestos(PARTE FINAL)

---

config-general/constantes.php
main-app/class/Estudiantes.php
main-app/class/servicios/MediaTecnicaServicios.php
main-app/compartido/matricula-boletin-curso-3.php
main-app/compartido/reporte-disciplina-sacar.php
main-app/docente/lista-clases.php
main-app/docente/listar-calificaciones.php
main-app/estudiante/verificar-carga.php

PES-628 -Modifying querys of the course enrollments

---

main-app/class/Estudiantes.php
main-app/compartido/informe-matriculas-retiradas.php
main-app/directivo/informes-todos.php
main-app/directivo/matriculas-retiradas-modal.php

PES-678 - Historial matrículas retiradas

---

config-general/idiomas.php
main-app/class/Movimientos.php
main-app/compartido/menu.php
main-app/directivo/includes/barra-superior-movimientos-financieros.php
main-app/directivo/movimientos.php
main-app/directivo/moviminetos-reportes-graficos.php

PES-636 - Pagina que muestre reportes gráficos

---

main-app/compartido/matricula-certificado-areas-3.php
main-app/compartido/matricula-libro-curso-2.php

HTF - avance soporte tagüi (MAIN)

---

main-app/compartido/matricula-boletin-curso-12.php
main-app/compartido/matricula-libro-curso-2.php

Se corrige mensaje de matrícula retirada en libro final y notas repetidas en períodos no cursados

HTF - Soporte tagüi (MAIN)

---

main-app/class/Boletin.php
main-app/compartido/matricula-boletin-curso-11.php

Se muestran observaciones disciplinarias de otros años

HTF - Soporte a nuevo gandhy (MAIN)

---

main-app/directivo/movimientos-actualizar.php
main-app/directivo/movimientos-editar.php
main-app/directivo/movimientos.php
main-app/js/Movimientos.js

PES-784 - [Hotfix] Improve financial modules

---

main-app/class/EvaluacionGeneral.php
main-app/directivo/evaluaciones-preguntas-actualizar.php
main-app/directivo/evaluaciones-preguntas.php
main-app/directivo/evaluaciones.php
main-app/js/Evaluaciones.js

PES-737 - Se crea interfaz para relacionar una evaluación a muchas preguntas

---

main-app/class/EvaluacionGeneral.php
main-app/class/PreguntaGeneral.php
main-app/class/Respuesta.php
main-app/directivo/evaluaciones-preguntas.php
main-app/directivo/preguntas-respuestas-actualizar.php
main-app/directivo/preguntas-respuestas.php
main-app/directivo/preguntas.php
main-app/directivo/respuesta.php
main-app/js/Preguntas.js

PES-740 - Se crea interfaz para relacionar las respuestas a una pregunta

---

config-general/constantes.php
main-app/class/Asignaciones.php
main-app/directivo/ajax-evaluado-option.php
main-app/directivo/asignaciones-actualizar.php
main-app/directivo/asignaciones-agregar.php
main-app/directivo/asignaciones-editar.php
main-app/directivo/asignaciones-eliminar.php
main-app/directivo/asignaciones-guardar.php
main-app/directivo/asignaciones.php
main-app/directivo/evaluaciones.php
main-app/js/Asignaciones.js

PES-738 - Se crea interfaz para asignación de evaluaciones

---

main-app/class/servicios/MediaTecnicaServicios.php
main-app/compartido/funciones.js
main-app/controlador/autentico.php
main-app/directivo/cursos-actualizar.php
main-app/directivo/cursos-agregar-modal.php
main-app/directivo/cursos-editar.php
main-app/directivo/cursos-guardar.php
main-app/guest/details.php

Pes 778 feed back sprint 22

---

config-general/verificar-usuario-bloqueado.php
main-app/acudiente/encuestas-pendientes.php
main-app/class/Asignaciones.php
main-app/compartido/body.php
main-app/compartido/encuestas-pendientes-contenido.php
main-app/compartido/modal-asignaciones.php
main-app/compartido/sintia-funciones-js.php
main-app/directivo/encuestas-pendientes.php
main-app/docente/encuestas-pendientes.php
main-app/estudiante/encuestas-pendientes.php

PES-535 - Script para determinar si un usuario tiene encuestas pendientes

---

main-app/compartido/encuestas-realizar.php
main-app/directivo/respuesta-guardar.php

PES-536 - Interfaz compartida para mostrar y llenar encuestas

---

main-app/docente/evaluaciones-resultados.php

ALTER TABLE mobiliar_academic.academico_actividad_evaluaciones ADD COLUMN eva_actividad varchar(255) NULL AFTER eva_formato;

 PES-424 -Importar notas de evaluacion

---

main-app/class/Asignaciones.php
main-app/directivo/asignaciones.php
main-app/directivo/encuestas-resultados.php
main-app/directivo/evaluaciones.php
main-app/directivo/includes/barra-superior-asignaciones.php
main-app/directivo/includes/barra-superior-resultados.php
main-app/directivo/includes/consulta-paginacion-asignaciones.php
main-app/directivo/includes/consulta-paginacion-resultados.php

PES-533 - Opción de ver listado los resultados en general de los usuarios por cuestionario

---

main-app/class/PreguntaGeneral.php
main-app/directivo/encuestas-detalles.php

PES-534 - Opción para ver detalles del cuestionario de un usuario en particular

---

main-app/docente/importar-info-detalles.php
main-app/docente/importar-info-guardar.php
main-app/docente/importar-info.php

PES-688 - Paso intermedio al importar información en docentes

---

config-general/constantes.php
main-app/class/Modulos.php
main-app/class/Respuesta.php
main-app/compartido/historial-acciones-guardar.php
main-app/compartido/menu-acudientes.php
main-app/compartido/menu-directivos.php
main-app/compartido/menu-docentes.php
main-app/directivo/asignaciones-editar.php
main-app/directivo/dev-modulos-actualizar.php
main-app/directivo/dev-modulos-editar.php
main-app/directivo/respuesta-agregar.php
main-app/directivo/respuesta-editar.php
main-app/directivo/respuesta.php

HTF - Mejoras de SPRINT-23

---

main-app/directivo/movimientos-agregar.php
main-app/directivo/movimientos-guardar.php

PES-789 -  Abono automático al crear factura

---

main-app/class/Movimientos.php
main-app/directivo/configuracion-finanzas.php
main-app/directivo/movimientos-factura-venta.php

PES-786 - Administrar T&C que aparecen al pie de la factura

---

main-app/directivo/sub-roles-actualizar.php
main-app/directivo/sub-roles-editar.php
main-app/js/Subroles.js

PES-684 - Subroles - Todo debe suceder en tiempo real al editar los subroles

---

main-app/acudiente/estudiantes.php
main-app/compartido/historial-acciones-guardar.php
main-app/compartido/menu-acudientes.php
main-app/compartido/menu-docentes.php
main-app/compartido/menu-estudiantes.php
main-app/directivo/estudiantes.php

PES-814 - Englobar opciones sueltas dentro de su módulo

---

main-app/class/UsuariosPadre.php
main-app/directivo/ajax-comprobar-usuario.php
main-app/directivo/includes/usuarios-editar-info-basica.php
main-app/directivo/usuarios-agregar.php
main-app/directivo/usuarios-editar.php
main-app/js/Usuarios.js

PES-731 - Al crear o editar, el usuario de acceso debe ser único en toda la tabla

---

main-app/acudiente/estudiantes.php
main-app/class/Modulos.php
main-app/compartido/menu-directivos.php
main-app/compartido/menu-docentes.php
main-app/compartido/menu-estudiantes.php
main-app/directivo/configuracion-sistema-guardar.php
main-app/directivo/estudiantes.php
main-app/directivo/includes/formulario-configuracion-contenido.php

Ejemplo de un cliente de prueba tipo company

PES-815 - Englobar los módulos y submódulos sueltos dentro de su módulo.

---

main-app/directivo/informe-libro-cursos-modal.php
main-app/directivo/informes-todos.php

PES-679 - Informes - Libro final por estudiante

---

main-app/compartido/informe-parcial-grupo-detalle.php
main-app/compartido/informe-parcial.php
main-app/directivo/informe-parcial-grupo-modal.php
main-app/directivo/informes-todos.php

PES-682 - Informes - Añadir informe parcial por estudiante

---

main-app/estudiante/cargas.php

**Contexto:** la coordinadora de ellen key reporta que al entrar a como un estudiante y seleccionar una carga, le muestra un mensaje que dice que la institución no tiene permiso de entrar a ese módulo, se valida y el archivo de ausencias.php pertenece al módulo 11 que es el módulo de clases y unidades donde se reportan las ausencias de los estudiante, se hace validación por módulo y se redirecciona a matricula.php

HTF - Se corrige redireccionamiento cuando un estudiante escoge una asignatura

---

main-app/class/Asignaciones.php
main-app/directivo/asignaciones-agregar.php
main-app/directivo/asignaciones-editar.php

PES-875 - Poner limites a los evaluadores y evaluados en cada asignación

---

main-app/compartido/encabezado.php

PES-897 - Mostrar mensaje con enlace para ir a responder las encuestas pendientes.

---

config-general/mensajes-informativos.php
main-app/class/Asignaciones.php
main-app/compartido/ajax-guardar-respuesta-encuesta.php
main-app/compartido/encuestas-pendientes-contenido.php
main-app/compartido/encuestas-realizar.php
main-app/js/Evaluaciones.js

PES-876 - Hacer cumplir los limites establecidos en las evaluaciones.

---

config-general/assets/css/cargando.css
main-app/class/CargaAcademica.php
main-app/class/Estudiantes.php
main-app/class/Inscripciones.php
main-app/class/componentes/barra-builder.php
main-app/class/componentes/barra-superior.php
main-app/class/componentes/filter/filter-cargas.php
main-app/class/componentes/filter/filter-inscripciones.php
main-app/class/componentes/filter/filter-matriculas.php
main-app/class/componentes/filter/filter-movimientos.php
main-app/class/componentes/result/cargas-tbody.php
main-app/class/componentes/result/inscripciones-tbody.php
main-app/class/componentes/result/matriculas-tbody.php
main-app/class/componentes/result/movimientos-tbody.php
main-app/directivo/cargas.php
main-app/directivo/estudiantes.php
main-app/directivo/includes/barra-superior-cargas-componente.php
main-app/directivo/includes/barra-superior-inscripciones-componente.php
main-app/directivo/includes/barra-superior-matriculas-componente.php
main-app/directivo/includes/barra-superior-movimientos-financieros-componente.php
main-app/directivo/inscripciones.php
main-app/directivo/movimientos.php

**Cargas**
**Matriculas**
**inscripciones**

PES 793 Real time

---

main-app/directivo/estudiantes-editar.php
main-app/directivo/includes/info-academica.php

PES-889 - Editar matricula

---

main-app/directivo/configuracion-institucion.php
main-app/directivo/dev-crear-nueva-bd.php
main-app/directivo/estudiantes-agregar.php
main-app/directivo/estudiantes-editar.php
main-app/directivo/includes/info-personal.php
main-app/directivo/includes/usuarios-editar-info-basica.php
main-app/directivo/usuarios-agregar.php

PES-879 - No permitir cualquier cosa en campos de celular o teléfono

---

config-general/constantes.php
main-app/directivo/cursos-editar.php
main-app/openAi/metodos.php

PES 799 -Aplicar openAi

---

config-general/assets-login-2023/js/pages/login.js
main-app/controlador/autentico.php
main-app/index.php

PES 842 remover campos institucion

---

main-app/compartido/matriculas-formato3-curso.php
main-app/compartido/matriculas-formato3.php
main-app/directivo/hoja-matricula-modal.php
main-app/directivo/informes-todos.php

PES-681 - Informes - Añadir hoja de matrícula por estudiante y por curso

---

main-app/class/UsuariosPadre.php
main-app/directivo/ajax-comprobar-cantidad-usuario.php
main-app/directivo/includes/usuarios-editar-info-basica.php
main-app/directivo/usuarios-agregar.php
main-app/js/Usuarios.js

PES-903 - Poner límites de creación de usuarios acorde al plan escogido

---

main-app/directivo/cursos-actualizar.php
main-app/directivo/cursos-agregar-modal.php
main-app/directivo/cursos-editar.php
main-app/docente/indicadores-guardar-fetch.php
main-app/docente/indicadores.php
main-app/docente/listar-indicadores-tbody.php
main-app/docente/listar-indicadores.php
main-app/estudiante/cargas-adicionales.php

PES-912 indicadores con open AI

---

main-app/compartido/funciones.js
main-app/compartido/noticias-contenido.php
main-app/compartido/noticias-reaccionar-fetch.php

Pes 695-reaccionar publicaicones

---

main-app/class/SocialComentarios.php
main-app/class/servicios/Servicios.php
main-app/compartido/comentario-li.php
main-app/compartido/comentarios.css
main-app/compartido/funciones.js
main-app/compartido/noticias-comentario-fetch.php
main-app/compartido/noticias-contenido.php
main-app/compartido/respuesta-li.php
main-app/compartido/sintia-funciones.php

PES 690 Responder comentarios

---

config-general/assets/css/comentarios-reacciones.css
main-app/class/SocialReacciones.php
main-app/compartido/funciones.js
main-app/compartido/noticias-contenido.php
main-app/compartido/noticias-reaccionar-fetch.php
main-app/compartido/publicaciones-lista.php
main-app/compartido/reacciones-lista-opciones.php
main-app/compartido/reacciones-lista-usuarios.php
main-app/compartido/reacciones-lista.php

PES -695 reaccionar publicaicones final

---

config-general/config.php

:white_check_mark: PES-1015 Cambio de proyecto firebase

---

config-general/constantes.php
main-app/class/Clases.php
main-app/docente/clases-agregar.php
main-app/docente/clases-editar.php

PES 696 video clases de 30 segundos en firebase

---

main-app/class/Clases.php
main-app/compartido/ajax-comentarios-preguntas.php
main-app/compartido/clase-comentario.php
main-app/compartido/clases-eliminar-comentarios.php
main-app/compartido/clases-guardar-comentarios.php
main-app/compartido/clases-ver-contenido.php
main-app/compartido/comentarios.css
main-app/compartido/funciones.js

Pes 691 responder comentarios clases async

---

main-app/class/CargaAcademica.php
main-app/class/Movimientos.php
main-app/class/UsuariosPadre.php
main-app/class/componentes/barra-builder.php
main-app/class/componentes/barra-superior.php
main-app/class/componentes/filter/filter-cargas.php
main-app/class/componentes/result/cargas-tbody.php
main-app/class/componentes/result/movimientos-tbody.php
main-app/compartido/carnet.php
main-app/compartido/indicadores-perdidos-curso-2.php
main-app/compartido/indicadores-perdidos-curso.php
main-app/compartido/matricula-boletin-curso-3.php
main-app/compartido/matricula-boletin-curso-9.php
main-app/directivo/ajax-comprobar-documento.php
main-app/directivo/ajax-estudiantes-agregar.php
main-app/directivo/ajax-estudiantes-editar.php
main-app/directivo/cargas.php
main-app/directivo/finanzas-cuentas.php
main-app/directivo/includes/barra-superior-cargas-componente.php
main-app/directivo/includes/usuarios-editar-info-basica.php
main-app/directivo/movimientos.php
main-app/directivo/usuarios-agregar.php
main-app/directivo/usuarios-editar.php
main-app/js/Usuarios.js

Revisión de boletines e informes para evitar datos quemados. En caso de haberlos, corregirlos.
El nombre de usuario no debe admitir espacios en blanco ni caracteres especiales.
Validar el numero de documento, en los boletins, para aplicar o no la función de number_format.
Cambiar a id_nuevo al mostrar los registros en los movimientos financieros.
Aplicar la expresión regular a los documentos al crear a los usuarios para evitar que se registren con puntos y sin puntos el mimso numero de documento.
Poder filtrar por periodo en las cargas académicas. (Checkbox para poder filtrar por uno o varios periodos)

PES-1035 - [Hotfix] Mejoras generales Parte 2 (MAIN)

---

main-app/class/Asignaciones.php
main-app/class/Respuesta.php
main-app/compartido/evaluaciones-generar-informe.php
main-app/directivo/asignaciones-asignados-eliminar.php
main-app/directivo/asignaciones-asignados.php
main-app/directivo/asignaciones-editar.php
main-app/directivo/asignaciones.php
main-app/directivo/includes/barra-superior-asignaciones-asignados.php
main-app/directivo/includes/consulta-paginacion-asignaciones-asignados.php
main-app/js/Asignaciones.js

Se trabajo la historia 1034 y se hicieron mejoras solicitadas por icolven

HTF - Para encuestas

---

librerias/Zindex/z-index.css
main-app/compartido/head.php
main-app/compartido/noticias-agregar-modal.php
main-app/directivo/informes-boletines-modal.php

HF-PES-1051 vista previa de formatos de boletines

---

main-app/class/Actividades.php

Este defect lo reportó Ellen key.
No se creó ningun ticket en JIRA.

HF - Corregir escape de caracteres en las tareas

---

config-general/assets-login-2023/js/pages/login.js
main-app/index.php

Estos fueron algunos detalles que encontró la QA Maria victoria.

HF - Corregir feedback en el login

---

main-app/compartido/informes-generales-sabanas.php

Esto fue reportado por el COALST

HF - Unificar consultas en sabanas de docentes

---

main-app/docente/cargas.php

Vamos a seguir calculando las notas normalmente hasta tener los triggers bien definidos

HF - Apuntar a la generación de informe tradicional

---

main-app/compartido/generar-informe.php

Esto es una medida temporal para agilizar la generación de informes de otras instituciones

HF - Se calculan notas por indicador solo para icolven (Temp)

---

main-app/class/Usuarios.php
main-app/compartido/modal-lista-usuarios.php
main-app/recuperar-clave-guardar.php
main-app/recuperar-clave.php

:pushpin:  PES-1065 remover opciones institución recuperar

---

config-general/page-info-contenido.php
main-app/class/Utilidades.php
main-app/directivo/areas.php
main-app/directivo/cargas.php
main-app/directivo/cursos.php
main-app/directivo/estudiantes.php
main-app/directivo/includes/barra-superior-cursos.php

🚀 PES-1046 Sa añade filtros para que el valor del los parámetros se valide el alfanumérico

---

main-app/class/Estudiantes.php
main-app/class/componentes/filter/filter-matriculas.php
main-app/class/componentes/result/matriculas-tbody.php
main-app/directivo/estudiantes.php
main-app/directivo/includes/barra-superior-matriculas-componente.php
main-app/directivo/includes/consulta-paginacion-estudiantes.php

Sé realizo actualización de filtros al momento de consultar por media técnica y se denegó el acceso a cambiar de grupo a los estudiantes de media técnica (temporalmente)

🚀 PES-1038 ajustar filtros por media técnica

---

main-app/class/Estudiantes.php

🚧 HF-PES-1111 listar estudiantes mediatecnica con notas faltantes

---

config-general/consulta-usuario-actual.php
config-general/verificar-usuario-bloqueado.php
documents/Releases/RELEASE33.md
main-app/class/Autenticate.php
main-app/class/Usuarios/Directivo.php
main-app/compartido/encabezado.php
main-app/compartido/perfil-actualizar.php
main-app/compartido/perfil-contenido.php
main-app/releases.php

1. [PES-1078] - Dar la posibilidad de ver el listado de sedes y cambiarse entre ellas.
[PES-1078]: https://oderman-group.atlassian.net/browse/PES-1078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Release de Developer a Main (Sprint 33)

---

main-app/class/CargaAcademica.php
main-app/class/componentes/ComponenteFiltros.php
main-app/class/componentes/filter/filter-cargas.php
main-app/directivo/cargas.php
main-app/directivo/includes/barra-superior-cargas-componente.php
main-app/directivo/includes/barra-superior-inscripciones-componente.php
main-app/directivo/inscripciones.php

Pes 662 obtimizar consultas

---

documents/Releases/RELEASE33.md
main-app/admisiones/admision.php
main-app/admisiones/bd-conexion.php
main-app/admisiones/formulario-guardar.php
main-app/admisiones/formulario.php
main-app/admisiones/index-guardar.php
main-app/class/Estudiantes.php
main-app/class/Inscripciones.php
main-app/class/Tables/BDT_aspirante.php
main-app/class/Tables/BDT_opciones_generales.php
main-app/class/Tables/BDT_tablas.php
main-app/class/componentes/result/inscripciones-tbody.php
main-app/compartido/funciones.js
main-app/directivo/configuracion-admisiones-guardar.php
main-app/directivo/configuracion-admisiones.php
main-app/directivo/estudiantes-actualizar.php
main-app/directivo/estudiantes-agregar.php
main-app/directivo/estudiantes-guardar.php
main-app/directivo/includes/info-personal.php
main-app/directivo/informes-boletines-modal.php
main-app/directivo/inscripciones-formulario-guardar.php
main-app/directivo/inscripciones-formulario.php
main-app/directivo/inscripciones-ocultar-aspirante.php
main-app/directivo/inscripciones.php
main-app/releases.php

Aqui van las historias HF que solicitó el cliente icolven para el módulo de admisiones.

Release de developer a producción para admisiones

---

config-general/constantes.php
main-app/compartido/matricula-libro-curso-1.php

Esto se hizo porque esta institución tiene muchos cursos el codigo de la mayoria está por encima de 11. Por ahora, para ellos se les mostrarán las notas en números en el libro final

HF - Mostrar notas en número para los EOA - ciruelos

---

main-app/class/CargaAcademica.php
main-app/compartido/matricula-boletin-curso-12.php

- Se incluye la cantidad de decimales que están en la configuración.

PES-1210 - Calcular nota del area considerando el grupo actual del estudiante

---

main-app/class/Boletin.php
main-app/directivo/estudiantes-promedios.php

🚀 HF-PES1211 mostrar nota calculada de los puestos

---

main-app/class/Boletin.php
main-app/compartido/agrupar-datos-boletin-periodos.php
main-app/compartido/matricula-boletin-curso-16.php
main-app/compartido/matricula-boletin-curso-19.php

Pes 1059 mejoras boletines 19 y 16

---

config-general/assets/js/app.js
config-general/assets/plugins/jquery-toast/dist/jquery.toast.min.css
main-app/class/CargaAcademica.php
main-app/compartido/ajax_carga_grupo.php
main-app/compartido/encabezado.php
main-app/compartido/modal-centralizado.php
main-app/directivo/estudiantes-cambiar-grupo-modal.php

Pes 1044 cambio de grupo

---

main-app/class/Disciplina.php
main-app/class/Tables/BDT_disciplina.php
main-app/class/componentes/ComponenteFiltros.php
main-app/class/componentes/filter/filter-comportamiento.php
main-app/class/componentes/result/cargas-tbody.php
main-app/class/componentes/result/comportamiento-tbody.php
main-app/directivo/comportamiento-actualizar-periodo.php
main-app/directivo/comportamiento-eliminar.php
main-app/directivo/comportamiento.php
main-app/directivo/cursos.php
main-app/directivo/includes/barra-superior-comportamiento.php
main-app/directivo/includes/consulta-paginacion-comportamiento.php
main-app/js/Comportamiento.js

PES-1223 - Manejo de las notas y observaciones de comportamiento que van al boletin

---

main-app/class/componentes/result/cargas-tbody.php
main-app/directivo/includes/barra-superior-comportamiento.php

PES-1223 - Se hace mejora para mostrar nombre del curso actual y tambien los filtros cuando se va desde cargas

---

main-app/class/CargaAcademica.php
main-app/compartido/matricula-certificado.php

PES-1313 - Los estudiantes no les aparecen algunas materias en los certificados (VA A LA MAIN)

---

config-general/assets/js/pages/steps/steps-data.js
config-general/assets/plugins/steps/steps.css
main-app/registro.php

PES-1161 - Permitir el auto-registro de una nueva institución (Paso 1 y paso 2) - (Correcciones Necesarias)

---

main-app/compartido/matricula-libro-curso-4.php

Se aplico solo en este formato ya que en el otro segun vi, se promedia de forma diferente

PES-1097 - EL TAGUI - Estudiantes retirados no se les debe promediar todos los periodos en el libro final - Formato Fast (1 y 2)

---

config-general/template-email-activar-cuenta-codigo.php
main-app/class/Sms.php
main-app/enviar-codigo.php
main-app/registro.php

PES-1162 - Activación de la institución nueva mediante código de verificación al correo (AVANCE)

---

config-general/assets-login-2023/js/pages/registro.js
main-app/bienvenida.php
main-app/registro-guardar.php
main-app/registro.php

PES-1174 - Envío de correo de bienvenida después de la activación de la cuenta nueva

---

.gitignore
config-general/mensajes-informativos.php
config-general/template-email-recuperar-clave-codigo.php
main-app/class/App/Mensajes_Informativos/Mensajes_Informativos.php
main-app/class/Usuarios.php
main-app/compartido/modal-lista-usuarios.php
main-app/js/recuperarClave.js
main-app/recuperar-clave-enviar-codigo.php
main-app/recuperar-clave-guardar.php
main-app/recuperar-clave-restaurar.php
main-app/recuperar-clave-validar-codigo.php
main-app/recuperar-clave.php

PES-1164 - Enviar código de verificación para recuperar contraseña al correo.

---

main-app/class/App/Socket/Socket.php
main-app/class/Sms.php
main-app/class/Usuarios.php
main-app/directivo/usuarios-update.php
main-app/enviar-codigo-sms.php
main-app/js/recuperarClave.js
main-app/recuperar-clave-enviar-codigo.php
main-app/recuperar-clave-notificar-directivos.php
main-app/recuperar-clave-validar-codigo.php

PES-1167 - Enviar código de recuperación de contraseña via SMS

---

config-general/verificar-usuario-bloqueado.php
main-app/docente/calificaciones-agregar.php
main-app/docente/calificaciones-editar.php
main-app/docente/importar-info-detalles.php
main-app/docente/importar-info-guardar.php
main-app/docente/listar-notas-indicadores.php
main-app/docente/notas-indicador.php

Se revisa y se detecta que lo que no esta permitiendo el listado de los indicadores al crear una calificación es por el método se modifico y se cambio el nombre al campo de ind_id, se le dio un AS diferente, se hizo el cambio en todos los lugares en que se llama a este metodo y se modifico donde se usa ese campo
Tambien se quita echo al momento de validar si el usaurio esta bloqueado ara que no muestre en prod "../estudiantes/"

PES-1340 - HTF - Corrección de errores reportados por Ellen Key

---

main-app/class/App/Academico/Matricula.php
main-app/class/App/Academico/boletin/Boletin.php
main-app/directivo/informe-parcial-grupo-modal.php

En primer commit se corrigen detalles encontrados inicial mente en archivo de informe parcial fast por estudiante donde se enviaban campos que debían ser de tipo string como si fuera intiger
En segundo commit se cambia informe del fast al antiguo mientras se revisa método Academico_boletin::datosBoletin en archivos de informe parcial fast

HTF - Se corrigen detalles encontrados en formato fast

---

main-app/compartido/perfil-contenido.php
main-app/compartido/reportes-sabanas.php
main-app/directivo/informe-reporte-sabana-modal.php
main-app/docente/cargas.php

El reporte de sabanas fast, esta trucando la información de las cargas, mientras se revisa el porque, se implementa el antiguo

HTF - Se usa reporte de sabana antiguo mientras se corrige el fast

---

main-app/class/App/Academico/Matriculas_Documentos.php
main-app/class/App/Academico/boletin/Boletin.php
main-app/class/App/Admiciones/Aspirantes.php
main-app/class/Tables/BDT_tablas.php
main-app/compartido/informes-documentos-inscripcion.php
main-app/directivo/informes-modal-documentos.php
main-app/directivo/informes-todos.php

HTF - Se crea archivo para ver documentación de la inscripción

---

main-app/class/CargaAcademica.php
main-app/compartido/informe-parcial.php

Antes de modificar el método se valido en que lugares se llamaba para no fracturar otros lugares en la plataforma
También se corrigió un error que había al llamar el método en estudiantes de MT

HTF - Se corrige método para consultar según el periodo escogido por el usuario

---

main-app/acudiente/estudiantes.php
main-app/acudiente/matriculas-adjuntar-documentos-agregar-modal.php
main-app/acudiente/matriculas-adjuntar-documentos-agregar.php
main-app/acudiente/matriculas-adjuntar-documentos-consultar.php
main-app/acudiente/matriculas-adjuntar-documentos-editar.php
main-app/acudiente/matriculas-adjuntar-documentos-eliminar.php
main-app/acudiente/matriculas-adjuntar-documentos.php
main-app/directivo/matriculas-adjuntar-documentos.php

adjuntar documentos estudiante acudiente

adjuntar documentos estudiante acudiente

---

main-app/docente/estudiantes.php
main-app/docente/matriculas-adjuntar-documentos-agregar-modal.php
main-app/docente/matriculas-adjuntar-documentos.php

adjuntar documentos estudiante docente

adjuntar documentos estudiante docente

---

main-app/directivo/matriculas-adjuntar-documentos-agregar.php
main-app/directivo/matriculas-adjuntar-documentos-consultar.php
main-app/directivo/matriculas-adjuntar-documentos-editar.php
main-app/directivo/matriculas-adjuntar-documentos-eliminar.php
main-app/docente/matriculas-adjuntar-documentos.php
main-app/js/matriculas-adjuntar-documentos.js

estandares del sistema y metodo para limpiar campos del formulario

estandares del sistema y metodo para limpiar campos del formulario

---

main-app/docente/indicadores-estudiantes-inclusion.php

indicadores personalizados inclusion

indicadores personalizados inclusion

---

main-app/class/Movimientos.php
main-app/directivo/moviminetos-reportes-graficos.php

HTF - Se tienen en cuenta los abonos en los gráficos financieros

---

main-app/class/Movimientos.php

HTF - no se descuentan los abonos en los egresos

---

main-app/directivo/historico-notas-filtros-modal.php

-- PRE REQUISISTOS PARA  FUCIoNAMIENTO DE HISTORIAL DE NOTAS
-- validar que los cursos tengan registrado valores de periodos en  academico_grados_periodos
SELECT * FROM mobiliar_academic_prod_prod.academico_grados_periodos   AS per  
WHERE per.institucion = 29
-- AND per.gvp_grado = ''
AND per.year = 2025;
-- si no tiene valores registrados ejecutar el procedimiento almacenado para calcular su valor 
-- ya sea por curos en especifico o por la institución completa 
-- inserta valores de periodo teniendo en cuenta la institución ,año y curso
CALL calcular_valor_peridos_cruso(29,2025,1);
-- inserta valores de periodo tenienendo en cuenta la institución ,año y curso
CALL calcular_valor_peridos_institucion(29,2025);

:rocket: HTF - listar  notas historicas a selecionados

---

main-app/class/Boletin.php
main-app/class/CargaAcademica.php
main-app/compartido/indicadores-perdidos-curso.php
main-app/compartido/matricula-boletin-curso-3.php

se agrega condicion para que se muestre tanto el indicador original como el de inclusion

se agrega condicion para que se muestre tanto el indicador original como el de inclusion

---

main-app/compartido/matricula-certificado-areas.php

AAC-16 - Se moficiar el número de matrícula a mostrar en los certificados académicos
